name: muku
description: 最小限の構成からなるべくプレーンで使い回し可能なOSS定期ゲーを作っていく取り組み

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9 # webは別かも？
  cloud_functions: ^3.2.10

  firebase_crashlytics: ^2.5.3
  firebase_analytics: ^9.1.2
  firebase_remote_config: ^2.0.2
  firebase_in_app_messaging: ^0.6.0+9

  # Riverpod 状態管理
  # https://riverpod.dev/docs/getting_started
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0

  # アイコン
  line_icons: ^2.0.1

  # 日本語フォント
  flutter_localizations:
    sdk: flutter

  # その他
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true