name: muku
description: 最小限の構成からなるべくプレーンで使い回し可能なOSS定期ゲーを作っていく取り組み

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9 # webは別かも？
  cloud_functions: ^3.2.10

  firebase_crashlytics: ^2.5.3
  firebase_analytics: ^9.1.2
  firebase_remote_config: ^2.0.2
  firebase_in_app_messaging: ^0.6.0+9

  # Riverpod 状態管理
  # https://riverpod.dev/docs/getting_started
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0

  # アイコン
  cupertino_icons: ^1.0.2
  line_icons: ^2.0.1

  # 日本語フォント
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.3.1

  # Webページを開く
  url_launcher: ^6.0.20 # 別ブラウザ
#  webview_flutter: ^3.0.2 # アプリ内

  # その他
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
#  assets:
#    - images/ # imagesフォルダの画像を読み取れるようにする

  uses-material-design: true

  # アイコン
  # 以下のコマンドを実行して配置
  # `flutter pub pub run flutter_launcher_icons:main`
#  flutter_icons:
#    android: true
#    ios: true
#    image_path: "lib/assets/icon_home_android.png"
  #  image_path_ios: 'lib/assets/icon_home_ios.png' # TODO: ios用は 背景付き マージン付き で別途作成
  #  image_path_android: 'lib/assets/icon_home_android.png'
  #  adaptive_icon_foreground: "lib/assets/icon_home_android.png"
  #  adaptive_icon_background: "lib/assets/white.png"